#!/usr/bin/env python3

import json
import sys
import ssl
import OpenSSL.crypto

# https://pyopenssl.org/en/stable/api/crypto.html
#print(ssl.OPENSSL_VERSION)
CA_FILE = '/etc/ssl/certs/ca-certificates.crt'


def getcert(addr):
    return ssl.get_server_certificate(addr)


def main(argv):
    host = argv[1]
    port = int(argv[2]) if len(argv) > 2 else 443
    cert = getcert((host, port))
    print(cert)

    x = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
    print(x.get_subject())
    print(x.get_issuer())
    print(x.get_serial_number())
    print(x.get_signature_algorithm())
    print(x.get_notBefore())
    print(x.get_notAfter())
    for i in range(x.get_extension_count()-1):
        e = x.get_extension(i)
        n = e.get_short_name()
        print("{} {}".format(n, e.__str__()))


if __name__ == "__main__":
    main(sys.argv)

